//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatRent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartment()
        {
            this.AddPhoto = new HashSet<AddPhoto>();
        }
    
        public int Id { get; set; }
        public int Id_Room { get; set; }
        public int Id_Metro { get; set; }
        public string Adress { get; set; }
        public int Price { get; set; }
        public int LivingSpace { get; set; }
        public int Id_User { get; set; }
        public byte[] Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddPhoto> AddPhoto { get; set; }
        public virtual Metro Metro { get; set; }
        public virtual User User { get; set; }
        public virtual Room Room { get; set; }
    }
}
