//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatRent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        public int Id { get; set; }
        public int Id_Room { get; set; }
        public int Id_Metro { get; set; }
        public string Adress { get; set; }
        public int Price { get; set; }
        public int LivingSpace { get; set; }
        public int Id_User { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Metro Metro { get; set; }
        public virtual User User { get; set; }
        public virtual Room Room { get; set; }
    }
}
